import { config } from "./config";

/**
 * Exact artist and track for YouTube's auto-generated uploads (issue #26).
 *
 * Uploads from a "- Topic" channel carry the song's metadata in their
 * description:
 *
 *   Provided to YouTube by Motown
 *
 *   Superstition · Stevie Wonder
 *
 *   Talking Book
 *   ...
 *   Auto-generated by YouTube.
 *
 * The official YouTube Data API returns that description (videos.list,
 * 1 quota unit per song). When it's there, it beats parsing the title. The
 * API's terms allow caching for up to 30 days; this cache lives in memory
 * only, for the session.
 */

const API = "https://www.googleapis.com/youtube/v3/videos";
const TIMEOUT_MS = 3000;

export interface YouTubeSong {
  title: string;
  artist: string;
}

/** The "Track · Artist · Artist" line of an auto-generated description, or null. */
export function parseAutoGenerated(description: string): YouTubeSong | null {
  if (!/Auto-generated by YouTube\.?\s*$/i.test(description.trim()) || !/^Provided to YouTube by /im.test(description)) return null;
  const line = description.split(/\r?\n/).map((l) => l.trim()).find((l) => l.includes(" · "));
  if (!line) return null;
  const [title, ...artists] = line.split(" · ").map((s) => s.trim()).filter(Boolean);
  if (!title || !artists.length) return null;
  return { title, artist: artists.join(", ") };
}

const cache = new Map<string, YouTubeSong | null>();

/** The song an auto-generated upload names, or null (no key, not auto-generated, or the API failed). */
export async function songFromYouTube(videoId: string | undefined): Promise<YouTubeSong | null> {
  if (!config.youtubeApiKey || !videoId || !/^[\w-]{11}$/.test(videoId)) return null;
  if (cache.has(videoId)) return cache.get(videoId) ?? null;
  try {
    const url = `${API}?${new URLSearchParams({ part: "snippet", id: videoId, key: config.youtubeApiKey })}`;
    const res = await fetch(url, { signal: AbortSignal.timeout(TIMEOUT_MS) });
    // Never log the URL: it holds the key.
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = (await res.json()) as { items?: Array<{ snippet?: { description?: string } }> };
    const song = parseAutoGenerated(data.items?.[0]?.snippet?.description ?? "");
    if (song) console.log(`[YouTube] ${videoId} is "${song.title}" by ${song.artist} (auto-generated upload)`);
    cache.set(videoId, song);
    return song;
  } catch (err) {
    // Not cached: the next request for this video tries again.
    console.warn(`[YouTube] Couldn't read video ${videoId}: ${err instanceof Error ? err.message : err}`);
    return null;
  }
}
