jest.mock("./config", () => ({ config: { youtubeApiKey: "", topic: "general" } }));

import { parseAutoGenerated, songFromYouTube } from "./youtube-metadata";

const AUTO = `Provided to YouTube by Motown

Superstition · Stevie Wonder

Talking Book

℗ 1972 Motown Records

Released on: 1972-10-28

Auto-generated by YouTube.`;

describe("parseAutoGenerated", () => {
  it("reads the track and artist from an auto-generated description", () => {
    expect(parseAutoGenerated(AUTO)).toEqual({ title: "Superstition", artist: "Stevie Wonder" });
  });

  it("joins several artists", () => {
    const d = AUTO.replace("Superstition · Stevie Wonder", "INDUSTRY BABY · Lil Nas X · Jack Harlow");
    expect(parseAutoGenerated(d)).toEqual({ title: "INDUSTRY BABY", artist: "Lil Nas X, Jack Harlow" });
  });

  it("ignores ordinary descriptions, even with a middle dot", () => {
    expect(parseAutoGenerated("New video! Song · Me\nFollow me on Twitch")).toBeNull();
  });
});

describe("songFromYouTube", () => {
  it("does nothing without a key", async () => {
    const fetchSpy = jest.spyOn(global, "fetch");
    expect(await songFromYouTube("dQw4w9WgXcQ")).toBeNull();
    expect(fetchSpy).not.toHaveBeenCalled();
  });
});
